# Generated by Django 5.0.3 on 2024-03-12 11:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('java', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('js', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('c', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('sql', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
