# Generated by Django 5.0.3 on 2024-03-12 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='c',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='language',
            name='java',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='language',
            name='js',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='language',
            name='python',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='language',
            name='sql',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='language',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang', to='app.student'),
        ),
    ]
